version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backend_app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: myappdb
      DATABASE_USER: myappuser
      DATABASE_PASSWORD: mypassword
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
